name: Node.js CI

on:
    push:
        branches: [ main, trying, staging ]
    pull_request:
        branches: [ main, trying, staging ]

jobs:
    build:

        runs-on: ubuntu-20.04

        strategy:
            matrix:
                node-version: [ 14.x, 16.x ]

        steps:
            -   uses: actions/checkout@v2
            -   name: Use Node.js ${{ matrix.node-version }}
                uses: actions/setup-node@v1
                with:
                    node-version: ${{ matrix.node-version }}
            #            -   run: npm ci    # use instead of install if we choose to commit the `package-lock.json`
            -   run: npm install
            -   run: npm run build --if-present
            -   run: npm test
                env:
                    CI: true

    codestyle:
        name: Code Format and Lints
        runs-on: ubuntu-20.04
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
            -   name: Install Dependencies
                run: npm install
            -   name: Code Format Check with Prettier
                run: npm run prettier -- --check .
            -   name: Check with Linter
                run: npm run lint
